spring:
  application:
    name : Backend API Test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  jpa:
    hibernate:
      ddl-auto: none # ddl.sql
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug